// Code generated by "stringer -linecomment -type Op"; DO NOT EDIT.

package mips

import "strconv"

const _Op_name = "addadduaddiaddiuandandidivdivumultmultunorororisllsllvsrasravsrlsrlvsubsubuxorxorilhillosltsltusltisltiubeqbgtzblezbnejjaljalrjrlblbulhlhulwsbshswmfhimflomthimtlotrap"

var _Op_index = [...]uint8{0, 3, 7, 11, 16, 19, 23, 26, 30, 34, 39, 42, 44, 47, 50, 54, 57, 61, 64, 68, 71, 75, 78, 82, 85, 88, 91, 95, 99, 104, 107, 111, 115, 118, 119, 122, 126, 128, 130, 133, 135, 138, 140, 142, 144, 146, 150, 154, 158, 162, 166}

func (i Op) String() string {
	i -= 1
	if i >= Op(len(_Op_index)-1) {
		return "Op(" + strconv.FormatInt(int64(i+1), 10) + ")"
	}
	return _Op_name[_Op_index[i]:_Op_index[i+1]]
}
