// Code generated by "stringer -linecomment -type Reg"; DO NOT EDIT.

package mips

import "strconv"

const (
	_Reg_name_0 = "$zero"
	_Reg_name_1 = "$v0$v1"
	_Reg_name_2 = "$t2"
	_Reg_name_3 = "$ra"
)

var (
	_Reg_index_1 = [...]uint8{0, 3, 6}
)

func (i Reg) String() string {
	switch {
	case i == 0:
		return _Reg_name_0
	case 2 <= i && i <= 3:
		i -= 2
		return _Reg_name_1[_Reg_index_1[i]:_Reg_index_1[i+1]]
	case i == 10:
		return _Reg_name_2
	case i == 31:
		return _Reg_name_3
	default:
		return "Reg(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
