// Code generated by "stringer -linecomment -type Reg"; DO NOT EDIT.

package mips

import "strconv"

const _Reg_name = "$zero$at$v0$v1$a0$a1$a2$a3$t0$t1$t2$t3$t4$t5$t6$t7$s0$s1$s2$s3$s4$s5$s6$s7$t8$t9$k0$k1$gp$sp$fp$ra$pc$hi$loCP0Reg0CP0Reg1BusCtrlConfigCP0Reg4CP0Reg5CP0Reg6CP0Reg7BadVaddrCountPortSizeCompareSRCauseEPCPRIdCP0Reg16CP0Reg17CP0Reg18CP0Reg19CP0Reg20CP0Reg21CP0Reg22CP0Reg23CP0Reg24CP0Reg25CP0Reg26CP0Reg27CP0Reg28CP0Reg29CP0Reg30CP0Reg31$f0$f1$f2$f3$f4$f5$f6$f7$f8$f9$f10$f11$f12$f13$f14$f15$f16$f17$f18$f19$f20$f21$f22$f23$f24$f25$f26$f27$f28$f29$f30$f31$0$1$2$3$4$5$6$7$8$9$10$11$12$13$14$15$16$17$18$19$20$21$22$23$24$25$26$27$28$29$30$31$cp3_0$cp3_1$cp3_2$cp3_3$cp3_4$cp3_5$cp3_6$cp3_7$cp3_8$cp3_9$cp3_10$cp3_11$cp3_12$cp3_13$cp3_14$cp3_15$cp3_16$cp3_17$cp3_18$cp3_19$cp3_20$cp3_21$cp3_22$cp3_23$cp3_24$cp3_25$cp3_26$cp3_27$cp3_28$cp3_29$cp3_30$cp3_31"

var _Reg_index = [...]uint16{0, 5, 8, 11, 14, 17, 20, 23, 26, 29, 32, 35, 38, 41, 44, 47, 50, 53, 56, 59, 62, 65, 68, 71, 74, 77, 80, 83, 86, 89, 92, 95, 98, 101, 104, 107, 114, 121, 128, 134, 141, 148, 155, 162, 170, 175, 183, 190, 192, 197, 200, 204, 212, 220, 228, 236, 244, 252, 260, 268, 276, 284, 292, 300, 308, 316, 324, 332, 335, 338, 341, 344, 347, 350, 353, 356, 359, 362, 366, 370, 374, 378, 382, 386, 390, 394, 398, 402, 406, 410, 414, 418, 422, 426, 430, 434, 438, 442, 446, 450, 452, 454, 456, 458, 460, 462, 464, 466, 468, 470, 473, 476, 479, 482, 485, 488, 491, 494, 497, 500, 503, 506, 509, 512, 515, 518, 521, 524, 527, 530, 533, 536, 542, 548, 554, 560, 566, 572, 578, 584, 590, 596, 603, 610, 617, 624, 631, 638, 645, 652, 659, 666, 673, 680, 687, 694, 701, 708, 715, 722, 729, 736, 743, 750}

func (i Reg) String() string {
	if i >= Reg(len(_Reg_index)-1) {
		return "Reg(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Reg_name[_Reg_index[i]:_Reg_index[i+1]]
}
